add menu loop

diff --git a/jirasik b/jirasik
--- a/jirasik
+++ b/jirasik
@@ -1,4 +1,28 @@
 #!/bin/env bash
+MYDIR="`dirname $0`"
 
-CHOICE=`gum choose $(ls *.sh | cut -d'.' -f1 | sort)`
-./"$CHOICE.sh"
+cd $MYDIR
+REALDIR="`dirname $(readlink jirasik)`"
+if [[ -z "$REALDIR" ]]; then
+    echo "error bye." > /dev/stderr
+    exit 1
+fi
+
+cd $REALDIR
+
+while :; do
+
+    CHOICE=`gum choose $(ls *.sh | cut -d'.' -f1 | sort) cancel`
+    if [[ -z "$CHOICE" ]]; then
+        echo "Cancelled. Bye." > /dev/stderr
+        exit 1
+    fi
+
+    if [[ "$CHOICE" == "cancel" ]]; then
+        echo "Cancelled. Bye." > /dev/stderr
+        exit 1
+    fi
+
+    ./"$CHOICE.sh" || exit
+
+done
